// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LeindaSaid_EntityFramework_Assinment3.Entities;

[PrimaryKey("CustomerId", "CustomerTypeId")]
[Table("CustomerCustomerDemo")]
public partial class CustomerCustomerDemo
{
    [Key]
    [Column("CustomerID")]
    [StringLength(5)]
    public string CustomerId { get; set; } = null!;

    [Key]
    [Column("CustomerTypeID")]
    [StringLength(10)]
    public string CustomerTypeId { get; set; } = null!;

    [ForeignKey("CustomerId")]
    [InverseProperty("CustomerCustomerDemos")]
    public virtual Customer Customer { get; set; } = null!;

    [ForeignKey("CustomerTypeId")]
    [InverseProperty("CustomerCustomerDemos")]
    public virtual CustomerDemographic CustomerType { get; set; } = null!;
}