// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LeindaSaid_EntityFramework_Assinment3.Entities;

[PrimaryKey("EmployeeId", "TerritoryId")]
public partial class EmployeeTerritory
{
    [Key]
    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Key]
    [Column("TerritoryID")]
    [StringLength(20)]
    public string TerritoryId { get; set; } = null!;

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeTerritories")]
    public virtual Employee Employee { get; set; } = null!;

    [ForeignKey("TerritoryId")]
    [InverseProperty("EmployeeTerritories")]
    public virtual Territory Territory { get; set; } = null!;
}